### ISSUE TITLE
building issues

### ISSUE THREAD

**Issue by oscer803** [ibm-watson-iot/iot-cpp#23]
Hi! 

I can't build the iot-cpp project according to the readme. 

If I follow the steps in the readme, I get a lot of errors when running make. 

Snippet from running make:
....
In file included from /wbh/deps/iot-cpp/src/IOTP_Client.cpp:43:0:
/wbh/deps/iot-cpp/src/IOTP_Client.h: At global scope:
/wbh/deps/iot-cpp/src/IOTP_Client.h:61:35: error: ‘mqtt::idelivery_token_ptr’ has not been declared
      void delivery_complete(mqtt::idelivery_token_ptr tok);
....

The problem seems to be that the mqtt::idelivery_token_ptr can't be found. If I run grep to locate the declaration, the closest thing I find is mqtt::delivery_token_ptr (without the i), from the paho c++ libs.

Can someone please help me out. 

Best regards,
Oscar Bergström

**Comment by oscer803** [comment]
Hi Loki,

I managed to build the iot-cpp if I downgrade the paho c++ lib to its' prerelease. Seems like a change in the master branch. 

I attach the patch to setup.sh. 

Best regards,
Oscar

[setup.diff.txt](https://github.com/ibm-watson-iot/iot-cpp/files/1025040/setup.diff.txt)

**Comment by Lokesh-K-Haralakatta** [comment]
Thx.. will fix the issue.
