### ISSUE TITLE
I Can't build and got "Undefined Reference" error!

### ISSUE THREAD

**Issue by Yasin40** [ibm-watson-iot/iot-cpp#32]
Hi, I Do All step descripted for installing this library and was successfully But at the " make" step , 
I got this error
`[ 88%] Linking CXX executable sampleManagedGateway
../src/libIOTP_GatewayClient.so: undefined reference to `OPENSSL_init_ssl'
../src/libIOTP_GatewayClient.so: undefined reference to `OpenSSL_version'
../src/libIOTP_GatewayClient.so: undefined reference to `OPENSSL_init_crypto'
../src/libIOTP_GatewayClient.so: undefined reference to `TLS_client_method'
collect2: error: ld returned 1 exit status
samples/CMakeFiles/sampleManagedGateway.dir/build.make:107: recipe for target 'samples/sampleManagedGateway' failed
make[2]: *** [samples/sampleManagedGateway] Error 1
CMakeFiles/Makefile2:621: recipe for target 'samples/CMakeFiles/sampleManagedGateway.dir/all' failed
make[1]: *** [samples/CMakeFiles/sampleManagedGateway.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
`
 Who Know How I can solve it ? or Have any Idea for solving?
Please Help Me ...

**Comment by icraggs** [comment]
Hi.  You'll need OpenSSL available to build this library.  If you're on Linux, it should be there already.  On other operating systems, you'll need to install it separately.

**Comment by Yasin40** [comment]
thanks icraggs,
I installed openssl before your notation on my ubuntu, but i got error!

**Comment by Yasin40** [comment]
Yes, I installed it .

**Comment by Yasin40** [comment]
thanks for your attention,
openssl version:
OpenSSL 1.0.2n  7 Dec 2017

**Comment by icraggs** [comment]
It works for me:

Ubuntu 16.04 LTS 
OpenSSL 1.0.2g 1 Mar 2016
gcc version 5.4.0

Packages installed:

dpkg -l | grep openssl
ii  libgnutls-openssl27:amd64   3.4.10-4ubuntu1.4  amd64        GNU TLS library - OpenSSL wrapper
ii  openssl                                  1.0.2g-1ubuntu4.13   amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python-openssl                      0.15.1-2build1            all          Python 2 wrapper around the OpenSSL library

dpkg -l | grep libssl
ii  libssl-dev:amd64   1.0.2g-1ubuntu4.13     amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc               1.0.2g-1ubuntu4.13     all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64  1.0.2g-1ubuntu4.13      amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.0.0:i386      1.0.2g-1ubuntu4.13      i386         Secure Sockets Layer toolkit - shared libraries

**Comment by Yasin40** [comment]
hello , again,

for me is:
dpkg -l |grep openssl
ii  libgnutls-openssl27:amd64  3.4.10-4ubuntu1.4  amd64 GNU TLS library OpenSSL wrapper
ii  openssl 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 amd64 Secure Sockets Layer toolkit - cryptographic utility
ii  openssl-blacklist 0.5-3 all Blacklists for OpenSSL RSA keys and tools
ii  python-openssl 0.15.1-2build1 all Python 2 wrapper around the OpenSSL library

dpkg -l |grep libssl
ii  libssl-dev:amd64 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 amd64 Secure Sockets Layer toolkit - development files
ii  libssl-doc 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1  all Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64 1.0.2g-1ubuntu4.13  amd64 Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 amd64 Secure Sockets Layer toolkit - shared libraries

**Comment by icraggs** [comment]
Thanks. It looks like the issue is that your libssl-dev is at 1.1.0, and this library requires 1.0.x.  
Looking through the Ubuntu package list, there is shown a 

libssl1.0-dev

you could try installing that.  I don't know if the two libssl-dev packages for 1.0.x and 1.1.x can coexist.  I'll upgrade my Ubuntu version soon, and I guess I'll find out then.
