### ISSUE TITLE
What's the status and plan for "Device Management update in progress"? 

### ISSUE THREAD

**Issue by nuodong** [ibm-watson-iot/iot-cpp#4]
README.md indicates that " Device Management update in progress".  It has been a long time since last commit. Any update on this?

**Comment by sathipal** [comment]
@nuodong there will be a focus on this library starting mid April, we ll have the Device Management sections covered hopefully by the end of Q2 2017.

**Comment by amitmangalvedkar** [comment]
@nuodong The Device Management APIs have been added in the [last release](https://github.com/ibm-watson-iot/iot-cpp/releases) which was made available on 12th May.
